### ISSUE TITLE
coverage directory contents inadvertently checked into Git, please remove

### ISSUE THREAD

**Issue by cstrong** [spdy-http2/spdy-transport#45]
spdy-transport includes a coverage directory that has a coverage.json file in it.
This is somehow picked up by istanbul in other unrelated projects and it wreaks havoc.
In general generated files such as coverage.json should never be checked into git.
Let me know if I am missing anything, but I believe this problem exists in the latest release

**Comment by cstrong** [comment]
`Error: ENOENT: no such file or directory, open '/Users/koruza/code/spdy-transport/lib/spdy-transport.js'
>>     at Error (native)
>>     at Object.fs.openSync (fs.js:640:18)
>>     at Object.fs.readFileSync (fs.js:508:33)
>>     at LookupStore.get (/usr/src/app/node_modules/istanbul/lib/store/fslookup.js:40:19)
>>     at HtmlReport.writeDetailPage (/usr/src/app/node_modules/istanbul/lib/report/html.js:406:67)
>>     at /usr/src/app/node_modules/istanbul/lib/report/html.js:484:26
>>     at AsyncFileWriter.processFile (/usr/src/app/node_modules/istanbul/lib/util/file-writer.js:93:9)
>>     at /usr/src/app/node_modules/async/lib/async.js:929:13
>>     at Immediate.process (/usr/src/app/node_modules/async/lib/async.js:897:25)
>>     at runCallback (timers.js:637:20)
>> Exited with code: 1.
Warning: Task "exec:coverage:html:test/unit" failed. Use --force to continue.`

**Comment by joshas** [comment]
Issue still exists in latest release v2.0.20. It adds almost 1MB of unnecessary data to node_modules directory when spdy-transport package is included.
Looks like fix was made here: https://github.com/spdy-http2/spdy-transport/pull/49
