### ISSUE TITLE
Error: Cannot find module 'obuf'

### ISSUE THREAD

**Issue by barbalex** [spdy-http2/spdy-transport#46]
When I run `npm start` in [my project](https://github.com/barbalex/ae2) on my new developer PC I get this error:

    PS C:\Users\alexa\ae2> npm start

    > ae2@0.1.0 start C:\Users\alexa\ae2
    > node scripts/start.js

    module.js:487
        throw err;
        ^

    Error: Cannot find module 'obuf'
        at Function.Module._resolveFilename (module.js:485:15)
        at Function.Module._load (module.js:437:25)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\alexa\ae2\node_modules\spdy-transport\lib\spdy-transport\protocol\base\parser.js:7:20)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! ae2@0.1.0 start: `node scripts/start.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the ae2@0.1.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\alexa\AppData\Roaming\npm-cache\_logs\2017-06-19T12_47_31_366Z-debug.log
    PS C:\Users\alexa\ae2>

It seems that `spdy-transport` causes this?

The PC runs:

- Windows 10
- node v8.1.2

This error does not occur on my old Windows 10 PC and my macOS running sierra.

**Comment by barbalex** [comment]
I wanted to get around this problem so ran:

    PS C:\Users\alexa\ae2> npm i --save-dev obuf
    + obuf@1.1.1
    added 1 package in 2.467s

The next `npm start` produced:

    PS C:\Users\alexa\ae2> npm start

    > ae2@0.1.0 start C:\Users\alexa\ae2
    > node scripts/start.js

    module.js:487
        throw err;
        ^

    Error: Cannot find module 'wbuf'
        at Function.Module._resolveFilename (module.js:485:15)
        at Function.Module._load (module.js:437:25)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\alexa\ae2\node_modules\spdy-transport\lib\spdy-transport\protocol\spdy\framer.js:11:19)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! ae2@0.1.0 start: `node scripts/start.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the ae2@0.1.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\alexa\AppData\Roaming\npm-cache\_logs\2017-06-19T12_59_09_292Z-debug.log
    PS C:\Users\alexa\ae2>

**Comment by barbalex** [comment]
It then goes on with `hpack.js`.

Seems like all dependencies are missing: https://github.com/spdy-http2/spdy-transport/blob/master/package.json#L19-L25

**Comment by ballPointPenguin** [comment]
relates to https://github.com/spdy-http2/spdy-transport/issues/51
