### ISSUE TITLE
Cannot find module 'hpack.js'

### ISSUE THREAD

**Issue by itsmoops** [spdy-http2/spdy-transport#51]
Hey there, my team just started a new project using the latest version of webpack-dev-server (2.7.1), and when starting up the server we are all consistently seeing the following error.

`Error: Cannot find module 'hpack.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/a6001382/analytics/analytics-q/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/hpack-pool.js:5:13)`

The issue is still persisting even after attempting to install hpack.js as a globally available dependency. Is there a way to resolve this?

**Comment by ballPointPenguin** [comment]
seeing the same, starting today

**Comment by itsmoops** [comment]
Hey @ballPointPenguin - I was able to resolve this issue. I found out that this wasn't exactly an issue with the package itself. Try running `npm i -g npm@latest-4` and try installing again. Evidently some versions of NPM don't correctly set the "main" field of package.json if the package contains a period like hpack.js.

**Comment by ballPointPenguin** [comment]
aha. Thank you @itsmoops

**Comment by Nolanus** [comment]
Updating npm did not solve the problem for me. I had to manually go into `node_modules/spdy-transport` and run `npm install` in there.
