### ISSUE TITLE
test broken on master for all versions of node

### ISSUE THREAD

**Issue by MylesBorins** [spdy-http2/spdy-transport#54]
```
  1 failing

  1) Framer http2 (v4) HEADERS should generate priority request frame:
     Uncaught TypeError: "value" argument is out of bounds
      at checkInt (buffer.js:1180:11)
      at Buffer.writeUInt32BE (buffer.js:1273:5)
      at WBuf.writeUInt32BE (node_modules/wbuf/index.js:281:15)
      at lib/spdy-transport/protocol/http2/framer.js:257:11
      at lib/spdy-transport/protocol/http2/framer.js:117:30
      at Framer._frame (lib/spdy-transport/protocol/http2/framer.js:41:3)
      at Framer.<anonymous> (lib/spdy-transport/protocol/http2/framer.js:110:10)
      at Array.forEach (<anonymous>)
      at Framer._continuationFrame (lib/spdy-transport/protocol/http2/framer.js:99:10)
      at lib/spdy-transport/protocol/http2/framer.js:246:10
      at done (lib/spdy-transport/utils.js:84:5)
      at next (lib/spdy-transport/utils.js:102:5)
      at afterWrite (node_modules/readable-stream/lib/_stream_writable.js:481:3)
      at _combinedTickCallback (internal/process/next_tick.js:144:20)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by MylesBorins** [comment]
seems to have been broken by wbuf 1.7.3, I'm assuming [this commit](https://github.com/indutny/wbuf/commit/6c8b8e06766ee0bcd19a1956abb1bbb8b3da7f0e)

ping @indutny

**Comment by indutny** [comment]
It is ` Uncaught RangeError [ERR_INVALID_OPT_VALUE]: The value "-2147483648" is invalid for option "value"`

**Comment by indutny** [comment]
Should be fixed by https://github.com/spdy-http2/spdy-transport/pull/55
